services:
  # ...keep existing 'backend' service

  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432  # enables connecting locally via psql
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: postgres
      - POSTGRES_DB: kronosweb_dev
      - POSTGRES_HOST_AUTH_METHOD: trust
    container_name: kronos-web
    volumes:
      - postgres_data:/var/lib/postgresql/data/